name: "Test"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://releases.nixos.org/nix/nix-2.3.7/install
    - uses: cachix/cachix-action@v8
      with:
        name: domenkozar
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-store -r /nix/store/dqlx77d224grs7ch39jhgfplf68mg6sl-python3.8-pre-commit-2.7.1
