name: "Test"
on:
  push:
jobs:
  tests:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
    - uses: cachix/cachix-action@v10
      with:
        name: domenkozar
    - run: nix-build -A git
